#!/usr/bin/env python3
'Output sorted summary of VIM plugin startup times in millisecs.'
# Mark Blakeney, Jan 2018
import os, sys, argparse, subprocess, tempfile
from pathlib import Path
from collections import defaultdict

HOME = Path.home()

# List of subdirs to exclude
EXCLUDED = ('autoload',)

opt = argparse.ArgumentParser(description=__doc__.strip())
opt.add_argument('-e', '--exe', default='vim',
        help='vim executable name, default="%(default)s"')
opt.add_argument('-n', '--num', type=int,
        help='limit output to given number of plugins')
args = opt.parse_args()

# Need file to log to and an empty file to edit
logfile = tempfile.NamedTemporaryFile('r')
tmpfile = tempfile.NamedTemporaryFile('r')
cmd = '{} -Xf --startuptime {} -cqa {}'.format(args.exe, logfile.name,
        tmpfile.name)
try:
    res = subprocess.run(cmd.split())
except Exception as e:
    sys.exit(e)

if res.returncode != 0:
    sys.exit('.. exited with {} error.'.format(args.exe))

# Create dict of paths and times
paths = defaultdict(float)
for line in logfile:
    if ': sourcing /' not in line:
        continue

    junk, junk, tstr, junk, fname = line.split()

    # Only concerned with personal plugins
    try:
        fpath = Path(fname).relative_to(HOME)
    except ValueError:
        continue

    paths[fpath] += float(tstr.rstrip(':'))

# Now remove any common path prefix
prefix = os.path.commonpath(paths)
paths = {Path(p).relative_to(prefix): v for p, v in paths.items()}

# Now assume plugin name is unique dir name in plugin dir and so tally
# times. We also exclude some subdirs.
times = defaultdict(float)
for path, val in paths.items():
    if len(path.parts) > 1 and path.parts[0] not in EXCLUDED:
        times[path.parts[1]] += val

# Output sorted results
if times:
    percent = 100. / sum(times.values())
    for ind, plugin in enumerate(sorted(times, key=times.get, reverse=True), 1):
        if args.num and ind > args.num:
            break

        v = times[plugin]
        print('{:4}: {:9.3f} ({:4.1f}%) {}'.format(ind, v, v * percent, plugin))
