#!/bin/bash
# User setup script.
# (C) Mark Blakeney, Jan 2018.

PROG="$(basename $0)"
NAME=${PROG%-*}

BINDIR="/usr/bin"
DOCDIR="/usr/share/doc/$NAME"

usage() {
    echo "Usage:"
    echo "sudo $PROG install|uninstall"
    echo
    echo "(-d option sets DESTDIR for install/uninstall)"
    exit 1
}

# Process command line options
DESTDIR=""
while getopts d: c; do
    case $c in
    d) DESTDIR="$OPTARG";;
    \?) usage;;
    esac
done

shift $((OPTIND - 1))

if [[ $# -ne 1 ]]; then
    usage
fi

cmd="$1"

DESTDIR=$(echo "$DESTDIR" | sed 's:/*$::')
if [[ -z "$DESTDIR" && $(id -un) != "root" ]]; then
    echo "Must be run as sudo/root."
    exit 1
fi

if [[ $cmd == "install" ]]; then
    install -CDv -m 755 -t $DESTDIR$BINDIR $NAME-setup
    install -CDv -m 755 -t $DESTDIR$BINDIR $NAME
    install -CDv -m 644 -t $DESTDIR$DOCDIR README.md

    # Also install HTML file if markdown is available
    if hash markdown &>/dev/null; then
	markdown README.md -o $DESTDIR$DOCDIR/README.html
    fi
elif [[ $cmd == "uninstall" ]]; then
    rm -rfv $DESTDIR$DOCDIR
    rm -rfv $DESTDIR$BINDIR/$NAME
    rm -rfv $DESTDIR$BINDIR/$NAME-setup
else
    usage
fi

exit 0
